### ISSUE TITLE
Quality of Adapters

### ISSUE THREAD

**Issue by MiroFurtado** [zphang/bert_on_stilts#4]
Hello! I am interested in whether you were able to get similar results to your paper using adapters rather than whole model tuning.

It seems like adapters might be less effective at holding the information received from an intermediate task as compared to tuning the whole BERT model. 

There also doesn't seem to be much documentation on Adapters in this code base - do you have any pointers of a good example in the code?

**Comment by zphang** [comment]
Sorry, just came across this issue. Apologies for the poor documentation on the adapters - they were something that I implemented quickly, and did not get around to documenting.

Long story short is that my results were consistent with those of the Adapter authors - decent performance, but slightly worse than full-scale fine-tuning. In addition, training is also somewhat slower (also to be expected).

With regards to updating the documentation, I am waiting on an upcoming big update from the HuggingFace guys in this week or so before revamping a bunch of the code, so I probably won't be extending the current documentation/implementation for now (sorry!). In the meantime, if you are interested in using the adapter, I believe the key change is to copy/modify the BertConfig JSON and set `use_adapter=true`. In addition, the model training script should be modified to have the optimizer only modify the adapter layer weights.

**Comment by MiroFurtado** [comment]
Great! And thanks for the reply, totally understand missing my issue amidst the noise :)
